;;;; package.lisp

(uiop:define-package #:fuse.controls
    (:use :cl)
  (:export
   :activated
   :activating-animation
   :adding-animation
   :alternate-root
   :android
   :back-button
   :back-button
   :blur
   :blur
   :bottom-bar-background
   :bottom-frame-background
   :button
   :button
   :button-base
   :circle
   :circular-range-behavior
   :clicked
   :client-panel
   :closure
   :cone-renderer
   :container
   :containing-text
   :content-control
   :cube-renderer
   :cylinder-renderer
   :deactivated
   :deactivating-animation
   :default-scroller
   :default-trigger
   :deferred
   :desaturate
   :deselected
   :direct-navigation
   :directional-light
   :dock-panel
   :double-clicked
   :double-tapped
   :draggable
   :drop-shadow
   :each
   :edge-navigation
   :edge-navigator
   :edge-swipe-animation
   :ellipse
   :enter-horizontal
   :enter-vertical
   :entered-force-field
   :entering-animation
   :entity
   :environment-light
   :exit-horizontal
   :exit-vertical
   :exited-force-field
   :exiting-animation
   :file-image-source
   :find-edges
   :frustum
   :graphics-view
   :grid
   :halftone
   :hierarchical-navigation
   :http-image-source
   :image
   :in-force-field-animation
   :instance
   :instantiator
   :interaction-completed
   :interactive-transform
   :interactive-transform
   :ios
   :java-script
   :keep-focus-in-view
   :keep-in-view
   :keep-in-view-common
   :layout-animation
   :layout-control
   :linear-navigation
   :linear-range-behavior
   :long-pressed
   :map-marker
   :map-view
   :mask
   :match
   :mesh-renderer
   :multi-density-image-source
   :multi-layout
   :multi-layout-panel
   :native-view-host
   :nav-enter-horizontal
   :nav-exit-horizontal
   :nav-remove-horizontal
   :navigation-bar
   :navigation-bar
   :navigator number
   :on-back-button
   :on-key-press
   :on-user-event
   :page
   :page-begin-loading
   :page-control
   :page-indicator
   :page-indicator-dot
   :page-loaded
   :page-view
   :pan-gesture
   :panel
   :path
   :path-shape
   :placeholder
   :point-attractor
   :point-light
   :pressed
   :progress-animation
   :pull-to-reload
   :range-animation
   :range-control
   :range-control-2-d
   :rectangle
   :regular-polygon
   :released
   :removing-animation
   :render-node
   :render-to-texture
   :resource-bool
   :resource-float
   :resource-float-2
   :resource-float-3
   :resource-float-4
   :resource-object
   :resource-string
   :resources
   :right-frame-background
   :root-viewport
   :rotate-gesture
   :rotation
   :rotation
   :router
   :scaling
   :scaling
   :scene
   :scroll-view
   :scroll-view-base
   :scrolled
   :scroller
   :scrolling-animation
   :select
   :selectable
   :selected
   :selection shadow
   :shear
   :shear
   :slider
   :slider
   :sphere-renderer
   :spot-light
   :spring
   :stack-panel
   :star
   :state
   :state-group
   :status-bar-background
   :status-bar-config
   :status-bar-config
   :swipe-gesture
   :swipe-navigate
   :swiped
   :swiping-animation
   :switch
   :switch
   :tapped
   :text
   :text
   :text-block
   :text-box
   :text-input
   :text-input
   :text-input-action-triggered
   :text-view
   :texture-image-source
   :timeline
   :toggle-control
   :top-frame-background
   :trackball
   :transform-3-d
   :transform-3-d
   :transition
   :translation
   :translation
   :user-event
   :video
   :viewbox
   :viewport
   :web-view
   :while-active
   :while-busy
   :while-can-go-back
   :while-can-go-forward
   :while-completed
   :while-contains-text
   :while-count
   :while-disabled
   :while-dragging
   :while-empty
   :while-enabled
   :while-failed
   :while-false
   :while-float
   :while-focus-within
   :while-focused
   :while-hovering
   :while-in-enter-state
   :while-in-exit-state
   :while-inactive
   :while-interacting
   :while-keyboard-visible
   :while-loading
   :while-navigating
   :while-not-empty
   :while-not-focused
   :while-page-loading
   :while-paused
   :while-playing
   :while-pressed
   :while-scrollable
   :while-scrolled
   :while-selected
   :while-string
   :while-swipe-active
   :while-true
   :while-visible
   :while-visible-in-scroll-view
   :while-window-landscape
   :while-window-portrait
   :while-window-size
   :with
   :wrap-panel
   :zoom-gesture))

(uiop:define-package #:whatevs
    (:use #:cl :xmls :uiop :fn :named-readtables :cl-ppcre :fuse.controls)

  ;;(:import-from :alexandria)
  )
